Feedback round 5
Blender-PLY-Project/blender pull request #221
Opened 2023-02-18 15:10 UTC by Kwonunn

Implements #195, #196, #197 and #219.

2023-02-18 15:24 UTC, Stroopwafe1 reviewed
In general: Take a close look at the style guide for classes and make sure the filebuffers are following the style guide. This way Hoogly has nothing to comment about anymore
https://wiki.blender.org/wiki/Style_Guide/C_Cpp#Class_Layout

2023-02-18 15:24 UTC, Stroopwafe1 commented on source/blender/io/ply/exporter/ply_file_buffer_ascii.hh
>    using FileBuffer::FileBuffer;
This using has to go above the public declaration according to the style guide

2023-02-18 15:24 UTC, Stroopwafe1 commented on source/blender/io/ply/exporter/ply_file_buffer_binary.hh
>    using FileBuffer::FileBuffer;
Same as ascii, using declaration above public

2023-02-19 15:12 UTC, Nathan-Rozendaal requested changes
Unit tests fail (they don't fail on development)

2023-02-27 17:32 UTC, Nathan-Rozendaal approved these changes

2023-02-27 17:32 UTC, merged